Jsons import
KNBEAN/kreator-map pull request #1
Opened 2019-02-28 13:05 UTC by Piotrek1697

2019-03-02 13:06 UTC, AnnLas requested changes
Brakuje dokumentacji, nazewnictwo miejscami niespójne.

2019-03-02 13:06 UTC, AnnLas commented on src/main/java/data/implementations/Edge.java
> +    public Edge(data.implementations.Node from_Node, data.implementations.Node to_Node){
Zrób importa data.implementations.Node oraz trzymaj się jednej konwencji nazewnictwa. ->
  public Edge(Node fromNode, Node toNode){
Sprawdź czy w całym kodzie jest spójne.

2019-03-04 20:40 UTC, KarolWys93 reviewed
Ogólnie wygląda to spoko. Komentarze dotyczące EdgeEntity dotyczą też wszystkich klas tego samego typu.

2019-03-04 20:40 UTC, KarolWys93 commented on src/main/java/Main.java
> +        //frame = new MainWindow(appName);
To powinno być wykomentowane?

2019-03-04 20:40 UTC, KarolWys93 commented on src/main/java/data/implementations/EdgeEntity.java
> +    public EdgeEntity(Node fromNode, Node toNode){
Jeżeli mamy kilka konstruktorów, które działają podobnie i różnią się jedynie ilością parametrów, to można je wywołać kaskadowo.
```suggestion
    public EdgeEntity(Node fromNode, Node toNode){
        this(fromNode.getId(), toNode.getId(), calculateLength(fromNode,toNode))
    }
```
To powinno wywołać kolejny konstruktor, który przyjmuje tylko idFrom, idTo, oraz length

2019-03-04 20:40 UTC, KarolWys93 commented on src/main/java/data/implementations/EdgeEntity.java
> +    public boolean equals(Object obj) {
Nadpisałbym też metodę hashCode, by mieć pewność, że ich wyniki equals i hashCode będą spójne.

2019-03-04 20:40 UTC, KarolWys93 commented on src/main/java/data/model/Edge.java
> +    Edge swapEnds();
Mam wątpliwości, czy ta metoda powinna być częścią interfejsu. Jak dla mnie taka funkcja jest za mało "abstrakcyjna" i sugeruje konkretną implementację. To tylko taka uwaga.

2019-03-04 20:40 UTC, KarolWys93 commented on src/test/java/JsonParserTest.java
> +    void shouldNotThrowError(){
Ten test jest redundantny. Zwróć uwagę, że w następnych testach z serii "shouldReturnAll*cośtam*" i tak robisz odczyt z pliku, który nie powinien się wywalić jak wszystko jest oki. Testuje się dwa razy to samo.

2019-03-04 20:40 UTC, AnnLas approved these changes

2019-03-05 17:45 UTC, Piotrek1697 commented on src/main/java/Main.java
> +        //frame = new MainWindow(appName);
Tak, bo nie ma tej klasy jak na razie

2019-03-07 12:57 UTC, merged